### ISSUE TITLE
如何找到第一个节点的？

### ISSUE THREAD

**Issue by xu-xiaofei** [chenjiandongx/magnet-dht#15]
您好，作者：
      完全去中心化的DHT 是如何寻找第一个节点的？我一直不是很清楚，您可以给我解答一下吗？
此外，我在使用Vuze 这个软件的时候自己上传文件做了种子，然后我自己下载自己的种子，为什么毫无反应，一直在寻找下载资源。敬请指教

**Comment by chenjiandongx** [comment]
随机伪造一个节点，利用服务器 tracker 加入到 DHT 网络中。
