### ISSUE TITLE
转换成种子一直超时？大概是什么问题

### ISSUE THREAD

**Issue by mainlove** [chenjiandongx/magnet-dht#17]
总是下载超时，这个可能是什么问题。。

我放了几个我迅雷可以下载的种子进去，也是timeout。。

![QQ图片20190412210718](https://user-images.githubusercontent.com/1627668/56039798-b323e700-5d67-11e9-9a40-cd434b1090c3.png)

**Comment by chenjiandongx** [comment]
大多数都是冷门磁链 下载不了正常 转换率并没有那么高

**Comment by mainlove** [comment]
我找了1w个磁力 也都没成功下载一个。。。
我感觉是哪里有问题，要么是我的服务器在罗马尼亚？ 我去找个其他vps试试，感觉代码配置都没啥问题

**Comment by Mrzy** [comment]
So did I, all failed, I don't know why

**Comment by a452669850** [comment]
![image](https://user-images.githubusercontent.com/44498323/58008734-9f666000-7b1f-11e9-8485-a10d10c287d8.png)卡在这里是啥情况啊 emmmm

**Comment by summertime-wu** [comment]
获取磁力连接的时候刚开始等了挺久，后面就刷刷的获取到链接

然后转换1100 多个链接，等了好久

最后全部失败了...
