### ISSUE TITLE
国内网络

### ISSUE THREAD

**Issue by pengwon** [chenjiandongx/magnet-dht#2]
这个在国内是不是不能用？我打开后一直没有反应。
![tim 20180707154909](https://user-images.githubusercontent.com/4396692/42408311-5565f770-81fd-11e8-9fd9-f8bd34a456c9.png)

**Comment by pengwon** [comment]
试了几次好像还是不行。可以贴张图看看如果成功的话再这两行下边显示啥吗？

**Comment by pengwon** [comment]
今天在我的香橙派上又试了几次，跟在PC上不太一样，弹出那两行信息后直接退了，
![image](https://user-images.githubusercontent.com/4396692/42443835-2c12c90c-83a1-11e8-8455-404e67dd88aa.png)求大神指点到底是什么问题，怎么解决？需要我提供哪些有用的信息。

**Comment by chenjiandongx** [comment]
@pengwon 我忘了说这点了，Windows 和 Linux 的线程/进程机制不太相同

我的服务器上的代码是这样的

![image](https://user-images.githubusercontent.com/19553554/42625499-7d19c11a-85fa-11e8-948a-80d2536d6e81.png)

**Comment by pengwon** [comment]
@chenjiandongx 多谢指点。可我这边还是不行。有什么调试手段能分析出我的问题出在哪里吗？

**Comment by pengwon** [comment]
@chenjiandongx 运行程序后redis一直查询不到有magnet
![image](https://user-images.githubusercontent.com/4396692/42743012-aa0b8276-88f2-11e8-987c-9afaaa842813.png)
![image](https://user-images.githubusercontent.com/4396692/42743018-b2f9116e-88f2-11e8-8f20-c5167048e6c8.png)
已经按照您说的修改了派上的代码

**Comment by chenjiandongx** [comment]
可以试着调 utils.py 里面的 NEIGHBOR_END 常量，增大到 14 或者 16，然后多关闭程序然后重新启动试试

**Comment by chenjiandongx** [comment]
@pengwon 重新拉取代码在本地跑试试，我优化了一下

**Comment by pengwon** [comment]
@chenjiandongx 可能是我这边网络问题，还是不行。在win10上需要特别开防火墙吗？我这倒是好几个bt工具都不好使，就transmission勉强能用。

**Comment by chenjiandongx** [comment]
要不你换个网络试一下吧 我这边防火墙也没关 也都可以正常运行

**Comment by pengwon** [comment]
@chenjiandongx 嗯，感谢耐心解答，谢谢。

**Comment by pengwon** [comment]
应该就是网络环境的问题，我所处的网络没有公网IP。在腾讯云上试了一下，可以跑起来。
