### ISSUE TITLE
获取不到其他node是什么情况？

### ISSUE THREAD

**Issue by Tyrone-Zhao** [chenjiandongx/magnet-dht#20]
直接访问可以访问，提示没有info_hash
但是运行程序获取不到邻居节点
![image](https://user-images.githubusercontent.com/37615298/58370750-b8667b00-7f3c-11e9-9e74-784b5f67d5d7.png)

**Comment by chenjiandongx** [comment]
最好使用公网 IP

**Comment by Tyrone-Zhao** [comment]
用的腾讯云服务器 依旧获取不到

**Comment by t1xingzhe** [comment]
放到阿里云上用不用开端口？

**Comment by chenjiandongx** [comment]
不需要开端口 安装好 python 环境和依赖就行了

![image](https://user-images.githubusercontent.com/19553554/69153995-28d00c80-0b1a-11ea-8e8c-5d12498e54d4.png)

**Comment by Tyrone-Zhao** [comment]
ok 谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈键冬 <notifications@github.com&gt;
发送时间: 2019年11月19日 22:16
收件人: chenjiandongx/magnet-dht <magnet-dht@noreply.github.com&gt;
抄送: Tyrone Zhao <tyrone-zhao@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[chenjiandongx/magnet-dht] 获取不到其他node是什么情况？ (#20)




不需要开端口 安装好 python 环境和依赖就行了
