### ISSUE TITLE
运行程序没有任何结果

### ISSUE THREAD

**Issue by cqboyone** [chenjiandongx/magnet-dht#21]
args = vars(parser.parse_args())返回值中的列表3项都为为False，不知道是为啥呢

**Comment by chenjiandongx** [comment]
安装好 python 环境和相关依赖

然后执行

```shell
$ python manage.py -s
```

![image](https://user-images.githubusercontent.com/19553554/69154299-bad81500-0b1a-11ea-9316-667b72398ed3.png)
