### ISSUE TITLE
因为贫穷,所以如何才能在1C2G的VPS上跑起来?

### ISSUE THREAD

**Issue by 23233** [chenjiandongx/magnet-dht#23]
目前的1C2G运行直接卡死毫无反应.
所以应该调整什么参数?

**Comment by chenjiandongx** [comment]
把 crawler.py 里面的 SLEEP_TIME 调大一点就 ok 了

![image](https://user-images.githubusercontent.com/19553554/69153805-d68eeb80-0b19-11ea-83a5-12bf0021014e.png)
