### ISSUE TITLE
怎样才能将magnet转换为torrent？

### ISSUE THREAD

**Issue by xi-mad** [chenjiandongx/magnet-dht#24]

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/71655752-5f34b480-2d73-11ea-962f-d8ecc560fd35.png)

**Comment by xi-mad** [comment]
一次也没有成功

**Comment by Wh0ale** [comment]
同样遇到相同的问题，请问是怎么解决的呢
