### ISSUE TITLE
为什么我跑出来全部是拒绝访问

### ISSUE THREAD

**Issue by 951956133** [chenjiandongx/magnet-dht#27]
![QQ截图20200323143152](https://user-images.githubusercontent.com/45568905/77288565-10177380-6d13-11ea-8498-bca621329cf1.png)
是因为我没用vpn吗

**Comment by chenjiandongx** [comment]
这个最好有一个公网的 IP，你有没有云主机？有的话可以把程序部署在上面

**Comment by 951956133** [comment]
那我去租个阿里云，您的服务器操作系统是用的linux吗



---原始邮件---
发件人: "陈键冬"<notifications@github.com&gt;
发送时间: 2020年3月23日(周一) 下午4:17
收件人: "chenjiandongx/magnet-dht"<magnet-dht@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"951956133"<951956133@qq.com&gt;;
主题: Re: [chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27)




 
这个最好有一个公网的 IP，你有没有云主机？有的话可以把程序部署在上面

**Comment by chenjiandongx** [comment]
肯定啦

**Comment by 951956133** [comment]
万分感谢 我是学生 刚开始学习编程 可能提的问题有点弱智 请你见谅...如果我后面有不懂的 大佬别嫌我烦呀



---原始邮件---
发件人: "陈键冬"<notifications@github.com&gt;
发送时间: 2020年3月23日(周一) 下午4:20
收件人: "chenjiandongx/magnet-dht"<magnet-dht@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"951956133"<951956133@qq.com&gt;;
主题: Re: [chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27)




 
肯定啦

**Comment by chenjiandongx** [comment]
礼貌提问的话，我有空也会友善回复的哈

**Comment by 951956133** [comment]
您好，我又来打扰了。
我买了一年的阿里云服务器，把代码放上去之后，是这样的。

我把防火墙关闭，还是跑不起来，您知道是什么原因吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈键冬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午4:34
收件人:&nbsp;"chenjiandongx/magnet-dht"<magnet-dht@noreply.github.com&gt;;
抄送:&nbsp;"无"<951956133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27)





 
礼貌提问的话，我有空也会友善回复的哈

**Comment by chenjiandongx** [comment]
图呢

**Comment by 951956133** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈键冬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午4:10
收件人:&nbsp;"chenjiandongx/magnet-dht"<magnet-dht@noreply.github.com&gt;;
抄送:&nbsp;"无"<951956133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27)





 
图呢

**Comment by 951956133** [comment]
请问方便加一下您的联系方式吗，我不会打扰您的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈键冬"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 下午4:10
收件人:&nbsp;"chenjiandongx/magnet-dht"<magnet-dht@noreply.github.com&gt;;
抄送:&nbsp;"无"<951956133@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27)





 
图呢

**Comment by chenjiandongx** [comment]
chenjiandongx 微信号



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 951956133 <notifications@github.com&gt;
发送时间: 2020年3月24日 16:50
收件人: chenjiandongx/magnet-dht <magnet-dht@noreply.github.com&gt;
抄送: 陈键冬 <chenjiandongx@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27)





 请问方便加一下您的联系方式吗，我不会打扰您的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"陈键冬"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月24日(星期二) 下午4:10 
 收件人:&amp;nbsp;"chenjiandongx/magnet-dht"<magnet-dht@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"无"<951956133@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [chenjiandongx/magnet-dht] 为什么我跑出来全部是拒绝访问 (#27) 
 
 
 
 
 
   
 图呢
