### ISSUE TITLE
远程服务器终止连接，是我本地的问题吗？

### ISSUE THREAD

**Issue by molsantto** [chenjiandongx/magnet-dht#4]
爬了一晚上，12小时，只有10万.
![qq 20180720084528](https://user-images.githubusercontent.com/16461005/42980100-4ae7d114-8c08-11e8-811b-74a6f249561d.jpg)

**Comment by molsantto** [comment]
还有个问题，越运行爬的越慢，现在基本上不动了

**Comment by chenjiandongx** [comment]
我也发现了这个问题，等我再看看怎么优化一下

**Comment by chenjiandongx** [comment]
@molsantto 你现在拉取最新的 commit 再重新运行一下哈

**Comment by molsantto** [comment]
跑了10分钟，全是远程主机关闭连接，没有一个磁力链接了。速度确实解决了，很快

**Comment by chenjiandongx** [comment]
这个需要有公网 ip 有没有服务器 放服务器上跑

**Comment by molsantto** [comment]
到单位了，单位垃圾双核电脑，一秒钟8次请求，速度还可以。太爽了。
![default](https://user-images.githubusercontent.com/16461005/43434004-7805e53a-94ac-11e8-8094-02438a4dda60.JPG)

**Comment by chenjiandongx** [comment]
不顺便 star 一下项目表示鼓励哈哈
