### ISSUE TITLE
程序无法正常运行

### ISSUE THREAD

**Issue by tetsaicn** [chenjiandongx/magnet-dht#5]
刚进去便是远程主机强迫关闭了连接 与 https://github.com/chenjiandongx/magnet-dht/issues/4 类似
或者有几率刚listen完什么都不说就退出了
或者还有可能卡在listen完，什么都不输出，既不抓取链接也不退出

**Comment by tetsaicn** [comment]
1* 3* 都是因为没有公网IP，即国内网络导致
2* linux线程问题
解决而之

**Comment by chenjiandongx** [comment]
@tetsaicn 线程问题看最新 commit

**Comment by tetsaicn** [comment]
@chenjiandongx 再说个，建议增加速度限制，挂在vps开了10秒就被踢了，vps强制挂起，原因疑似ddos别的主机......

**Comment by chenjiandongx** [comment]
crawler.py 里的 SLEEP_TIME 延迟时间给它调长一点就 ok 啦
