### ISSUE TITLE
冬哥你好

### ISSUE THREAD

**Issue by cexll** [chenjiandongx/magnet-dht#7]
请问运行该脚本的硬性条件是必须要有公网IP,关闭防火墙吗?
我在虚拟机试着运行了但是没有反应
系统环境: deepin 15.8 Python3.6 已安装 pip环境

**Comment by cexll** [comment]
现在运行之后会导致网络出现无法上网,上网慢等问题(会出现无法上网,需要关闭脚本,重启电脑重启路由器才恢复)
请问这是我的问题吗?

**Comment by chenjiandongx** [comment]
确实需要有一个公网 ip 这个脚本会占用大量的带宽资源 所以你上诉的问题应该是正常的 我以前也出现过
