### ISSUE TITLE
你好,爬出来的 magnet:?xt=u这样的链接 在迅雷里 解析失败

### ISSUE THREAD

**Issue by xieh1995** [chenjiandongx/magnet-dht#9]
你好,爬出来的 magnet:?xt=u这样的链接 在迅雷里 解析失败

**Comment by xieh1995** [comment]
应该是aria2c没有运作 不知道怎么回事
![image](https://user-images.githubusercontent.com/19343192/50412921-30256200-0846-11e9-8e9d-5e91a5cd5a6e.png)
![image](https://user-images.githubusercontent.com/19343192/50412929-374c7000-0846-11e9-8208-7ca02b9f8e9d.png)

**Comment by chenjiandongx** [comment]
解析只有一定几率能成功而已 毕竟大部分资源都是冷门资源

**Comment by xieh1995** [comment]
![image](https://user-images.githubusercontent.com/19343192/50414120-9c0bc880-084e-11e9-88de-25c4d1340b8a.png)
转成种子文件 是存放在哪里的
